issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/nsql(@1269406277)?:ref:refs/heads/main$
claim_pattern:
  repository_id: ^1269406277$
  repository_owner_id: ^114402558$
  runner_environment: ^self-hosted$
  ref: ^refs/heads/main$
  event_name: ^(push|workflow_dispatch)$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/rust-auto-tag\.yml@(b2c97f0c98c09099d19696089e55f1e95bd6ac1d|d9016b2889c88f1ec99bfe9d7262343a759e4b69)$
  job_workflow_sha: ^(b2c97f0c98c09099d19696089e55f1e95bd6ac1d|d9016b2889c88f1ec99bfe9d7262343a759e4b69)$
permissions:
  contents: write
