name: Tag release
'on':
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write
concurrency:
  group: auto-tag
  cancel-in-progress: false
jobs:
  tag:
    uses: fredrir/infra/.github/workflows/rust-auto-tag.yml@eb764b837d1fd10cb71fde1963500854aaef5d6c
