name: Tag release
'on':
  push:
    branches:
    - main
    paths-ignore:
    - .github/**
    - '**.md'
    - cliff.toml
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write
concurrency:
  group: auto-tag
  cancel-in-progress: false
jobs:
  tag:
    uses: fredrir/infra/.github/workflows/rust-auto-tag.yml@145594b5b2d8a2d124f777e2a7962bbf8c428a3a
