name: Tag release
'on':
  push:
    branches:
    - main
    paths-ignore:
    - .github/**
    - '**.md'
    - cliff.toml
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write
concurrency:
  group: auto-tag
  cancel-in-progress: false
jobs:
  tag:
    uses: fredrir/infra/.github/workflows/rust-auto-tag.yml@ca94d69c9751fed555f14be14ec341b15e127e38
