name: Release
on:
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  attestations: write
  artifact-metadata: write
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false
jobs:
  release:
    uses: fredrir/infra/.github/workflows/rust-release.yml@f44c0e6b90d5e3e1d62a202924b6ab1d0d34ecdd
